CREATE TABLE "cities" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"province" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "clinics" ADD COLUMN "province" text;--> statement-breakpoint
ALTER TABLE "clinics" ADD COLUMN "city_id" integer;--> statement-breakpoint
CREATE UNIQUE INDEX "cities_name_province_unique" ON "cities" USING btree ("name","province");--> statement-breakpoint
CREATE INDEX "cities_province_idx" ON "cities" USING btree ("province");--> statement-breakpoint
ALTER TABLE "clinics" ADD CONSTRAINT "clinics_city_id_cities_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."cities"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
-- Seed the cities a clinic is plausibly in. NOT exhaustive by design: the write path
-- finds-or-creates, so a town missing here costs one keystroke rather than blocking an
-- onboarding. What the seed buys is that everyone typing "Lahore" lands on one row.
-- ON CONFLICT DO NOTHING so re-running is safe and a city added by hand is never
-- clobbered by a later re-seed.
INSERT INTO "cities" ("name", "province") VALUES
  ('Islamabad', 'ict'),
  ('Lahore', 'punjab'),
  ('Faisalabad', 'punjab'),
  ('Rawalpindi', 'punjab'),
  ('Multan', 'punjab'),
  ('Gujranwala', 'punjab'),
  ('Sargodha', 'punjab'),
  ('Sialkot', 'punjab'),
  ('Bahawalpur', 'punjab'),
  ('Sheikhupura', 'punjab'),
  ('Jhang', 'punjab'),
  ('Rahim Yar Khan', 'punjab'),
  ('Gujrat', 'punjab'),
  ('Kasur', 'punjab'),
  ('Sahiwal', 'punjab'),
  ('Okara', 'punjab'),
  ('Wah Cantonment', 'punjab'),
  ('Dera Ghazi Khan', 'punjab'),
  ('Chiniot', 'punjab'),
  ('Kamoke', 'punjab'),
  ('Hafizabad', 'punjab'),
  ('Muzaffargarh', 'punjab'),
  ('Khanewal', 'punjab'),
  ('Mandi Bahauddin', 'punjab'),
  ('Jhelum', 'punjab'),
  ('Attock', 'punjab'),
  ('Vehari', 'punjab'),
  ('Burewala', 'punjab'),
  ('Kot Addu', 'punjab'),
  ('Daska', 'punjab'),
  ('Gojra', 'punjab'),
  ('Mianwali', 'punjab'),
  ('Bhalwal', 'punjab'),
  ('Toba Tek Singh', 'punjab'),
  ('Chishtian', 'punjab'),
  ('Pakpattan', 'punjab'),
  ('Narowal', 'punjab'),
  ('Layyah', 'punjab'),
  ('Bahawalnagar', 'punjab'),
  ('Lodhran', 'punjab'),
  ('Rajanpur', 'punjab'),
  ('Chakwal', 'punjab'),
  ('Jaranwala', 'punjab'),
  ('Kharian', 'punjab'),
  ('Nankana Sahib', 'punjab'),
  ('Ahmadpur East', 'punjab'),
  ('Khushab', 'punjab'),
  ('Wazirabad', 'punjab'),
  ('Arifwala', 'punjab'),
  ('Haroonabad', 'punjab'),
  ('Shakargarh', 'punjab'),
  ('Murree', 'punjab'),
  ('Bhakkar', 'punjab'),
  ('Sadiqabad', 'punjab'),
  ('Kabirwala', 'punjab'),
  ('Mian Channu', 'punjab'),
  ('Talagang', 'punjab'),
  ('Pattoki', 'punjab'),
  ('Hasilpur', 'punjab'),
  ('Kamalia', 'punjab'),
  ('Muridke', 'punjab'),
  ('Sambrial', 'punjab'),
  ('Taxila', 'punjab'),
  ('Jalalpur Jattan', 'punjab'),
  ('Depalpur', 'punjab'),
  ('Fort Abbas', 'punjab'),
  ('Pindi Bhattian', 'punjab'),
  ('Shorkot', 'punjab'),
  ('Chunian', 'punjab'),
  ('Sarai Alamgir', 'punjab'),
  ('Karachi', 'sindh'),
  ('Hyderabad', 'sindh'),
  ('Sukkur', 'sindh'),
  ('Larkana', 'sindh'),
  ('Shaheed Benazirabad', 'sindh'),
  ('Mirpur Khas', 'sindh'),
  ('Jacobabad', 'sindh'),
  ('Shikarpur', 'sindh'),
  ('Khairpur', 'sindh'),
  ('Dadu', 'sindh'),
  ('Tando Allahyar', 'sindh'),
  ('Tando Adam', 'sindh'),
  ('Badin', 'sindh'),
  ('Thatta', 'sindh'),
  ('Ghotki', 'sindh'),
  ('Kandhkot', 'sindh'),
  ('Kashmore', 'sindh'),
  ('Umerkot', 'sindh'),
  ('Sanghar', 'sindh'),
  ('Matiari', 'sindh'),
  ('Naushahro Feroze', 'sindh'),
  ('Jamshoro', 'sindh'),
  ('Moro', 'sindh'),
  ('Rohri', 'sindh'),
  ('Shahdadkot', 'sindh'),
  ('Kotri', 'sindh'),
  ('Tando Muhammad Khan', 'sindh'),
  ('Sehwan', 'sindh'),
  ('Mehar', 'sindh'),
  ('Nagarparkar', 'sindh'),
  ('Mithi', 'sindh'),
  ('Peshawar', 'kpk'),
  ('Mardan', 'kpk'),
  ('Mingora', 'kpk'),
  ('Kohat', 'kpk'),
  ('Abbottabad', 'kpk'),
  ('Dera Ismail Khan', 'kpk'),
  ('Nowshera', 'kpk'),
  ('Charsadda', 'kpk'),
  ('Swabi', 'kpk'),
  ('Mansehra', 'kpk'),
  ('Bannu', 'kpk'),
  ('Haripur', 'kpk'),
  ('Timergara', 'kpk'),
  ('Batkhela', 'kpk'),
  ('Hangu', 'kpk'),
  ('Karak', 'kpk'),
  ('Chitral', 'kpk'),
  ('Tank', 'kpk'),
  ('Lakki Marwat', 'kpk'),
  ('Daggar', 'kpk'),
  ('Takht Bhai', 'kpk'),
  ('Topi', 'kpk'),
  ('Havelian', 'kpk'),
  ('Dir', 'kpk'),
  ('Parachinar', 'kpk'),
  ('Battagram', 'kpk'),
  ('Alpuri', 'kpk'),
  ('Quetta', 'balochistan'),
  ('Turbat', 'balochistan'),
  ('Khuzdar', 'balochistan'),
  ('Chaman', 'balochistan'),
  ('Hub', 'balochistan'),
  ('Sibi', 'balochistan'),
  ('Zhob', 'balochistan'),
  ('Gwadar', 'balochistan'),
  ('Dera Murad Jamali', 'balochistan'),
  ('Dera Allah Yar', 'balochistan'),
  ('Loralai', 'balochistan'),
  ('Mastung', 'balochistan'),
  ('Kharan', 'balochistan'),
  ('Pasni', 'balochistan'),
  ('Nushki', 'balochistan'),
  ('Kalat', 'balochistan'),
  ('Usta Muhammad', 'balochistan'),
  ('Bela', 'balochistan'),
  ('Jiwani', 'balochistan'),
  ('Muzaffarabad', 'ajk'),
  ('Mirpur', 'ajk'),
  ('Kotli', 'ajk'),
  ('Rawalakot', 'ajk'),
  ('Bhimber', 'ajk'),
  ('Bagh', 'ajk'),
  ('Pallandri', 'ajk'),
  ('Hattian Bala', 'ajk'),
  ('Gilgit', 'gb'),
  ('Skardu', 'gb'),
  ('Chilas', 'gb'),
  ('Gahkuch', 'gb'),
  ('Khaplu', 'gb'),
  ('Astore', 'gb'),
  ('Karimabad', 'gb')
ON CONFLICT ("name", "province") DO NOTHING;