#!/usr/bin/env bash
#
# Installs FlexicaAI's scheduled jobs on a Linux host.
#
#   sudo ./deploy/install-cron.sh core     # the 6 jobs that need no API
#   sudo ./deploy/install-cron.sh all      # those + the 2 WhatsApp ones (8 total)
#   ./deploy/install-cron.sh check         # verify what's installed (no root needed)
#   ./deploy/install-cron.sh print [core|all]   # show the crontab without writing it
#
# WHY TWO MODES: only `recalls` and `reminders` need an API (WhatsApp — no job touches
# Whisper or Claude). The other six are pure database work and are gated on having
# real clinics, not on keys, and those triggers arrive independently. See delta D-19.
#
# LINUX + PRODUCTION ONLY. This writes /etc/cron.d and /etc/flexicaai as root, so it
# cannot run on a Windows dev box — and should not run on any dev box: `recalls` and
# `reminders` SEND WhatsApp messages to whatever numbers are in the database, and the
# send path has no NODE_ENV guard. Pointed at a seeded dev DB with provider keys set,
# it would message real phone numbers. To exercise a job locally, curl it by hand; to
# see what would be installed, use `print`.
#
# WHY A SCRIPT AT ALL: a job that is never invoked raises no error, so a botched
# install is silent — the failure mode is "recalls stopped going out three weeks ago
# and nobody noticed". This checks the secret actually authenticates BEFORE writing
# anything, and tells you how to confirm the jobs ran.
set -euo pipefail

MODE="${1:-}"
APP_URL="${APP_URL:-http://127.0.0.1:3000}"
RUN_USER="${RUN_USER:-flexica}"
ENV_FILE="${ENV_FILE:-/etc/flexicaai/cron.env}"
CRON_FILE="${CRON_FILE:-/etc/cron.d/flexicaai}"
APP_ENV="${APP_ENV:-.env.local}"

# ── The jobs. ONE definition; everything else is generated from it. ────────────
# schedule|path|needs_api|description
JOBS=$(cat <<'EOF'
0 9 * * *|recalls|whatsapp|Recalls: patients due for a follow-up visit
0 18 * * *|reminders|whatsapp|Day-before appointment reminders
0 2 * * *|expenses|-|Recurring clinic expenses -> materialise the ones now due
5 2 * * *|company-expenses|-|Recurring FlexicaAI company expenses
0 3 * * *|billing|-|Subscription sweep: active <-> past_due as time passes
30 3 * * *|reconcile|-|Sales reconciliation: re-derive any drifted ledger row
45 3 * * *|log-retention|-|Prune activity_logs past the retention window (no-op until set)
*/10 * * * *|scribe-recover|-|Fail scribe runs the process died in the middle of
EOF
)

die() { echo "error: $*" >&2; exit 1; }
need_root() { [ "$(id -u)" -eq 0 ] || die "run with sudo (writing $CRON_FILE)"; }

selected() {
  # $1 = core|all
  while IFS='|' read -r sched path api desc; do
    [ -n "$path" ] || continue
    if [ "$1" = "core" ] && [ "$api" != "-" ]; then continue; fi
    printf '%s|%s|%s|%s\n' "$sched" "$path" "$api" "$desc"
  done <<< "$JOBS"
}

render() {
  cat <<EOF
# FlexicaAI scheduled jobs — generated by deploy/install-cron.sh ($1 set).
# Do not hand-edit; re-run the script instead.
#
# Calls 127.0.0.1 directly so a job never traverses nginx (no proxy_read_timeout, no
# TLS) and the secret never leaves the loopback interface. \`curl -f\` makes an HTTP
# error a non-zero exit, so cron reports a 401/503 instead of passing silently.
# Times are in the SERVER'S timezone — the same clock availability and "tomorrow"
# reminders read from. Check it with \`timedatectl\` before trusting the 09:00/18:00 slots.
SHELL=/bin/sh
PATH=/usr/local/bin:/usr/bin:/bin
MAILTO=""
EOF
  while IFS='|' read -r sched path api desc; do
    [ -n "$path" ] || continue
    printf '\n# %s\n%-12s %s  . %s; curl -fsS -m 300 -H "Authorization: Bearer $CRON_SECRET" "%s/api/cron/%s" >/dev/null\n' \
      "$desc" "$sched" "$RUN_USER" "$ENV_FILE" "$APP_URL" "$path"
  done < <(selected "$1")
}

read_secret() {
  if [ -n "${CRON_SECRET:-}" ]; then echo "$CRON_SECRET"; return; fi
  [ -f "$APP_ENV" ] || die "CRON_SECRET not set and $APP_ENV not found (set CRON_SECRET= or APP_ENV=)"
  grep -m1 '^CRON_SECRET=' "$APP_ENV" | cut -d= -f2- | tr -d '"'"'"'\r'
}

preflight() {
  local secret="$1"
  [ -n "$secret" ] || die "CRON_SECRET is empty — the app will refuse to run jobs in production (503)"
  echo "  checking the app answers on $APP_URL ..."
  curl -fsS -m 15 "$APP_URL/api/ping" >/dev/null 2>&1 \
    || die "no response from $APP_URL — is the app running? (systemctl status flexicaai)"
  echo "  checking the secret authenticates ..."
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' -m 120 \
    -H "Authorization: Bearer $secret" "$APP_URL/api/cron/reconcile")
  case "$code" in
    200) echo "  ok — a real job ran and returned 200" ;;
    401) die "the app rejected this secret (401). CRON_SECRET here does not match the app's." ;;
    503) die "the app has no CRON_SECRET set (503) — add it to the app's environment and restart." ;;
    *)   die "unexpected response $code from /api/cron/reconcile" ;;
  esac
}

case "$MODE" in
  print)
    render "${2:-all}"
    ;;

  check)
    if [ ! -f "$CRON_FILE" ]; then
      echo "NOT INSTALLED — $CRON_FILE does not exist. No scheduled job is running."
      exit 1
    fi
    echo "installed: $CRON_FILE"
    grep -c 'api/cron/' "$CRON_FILE" | sed 's/^/  jobs: /'
    grep -o 'api/cron/[a-z-]*' "$CRON_FILE" | sed 's|api/cron/|    |'

    # The classic silent break: the cron line runs as $u and sources the env file, so if
    # $u cannot read it, EVERY job fails nightly and only the system log ever says so.
    CRON_AS=$(grep -m1 'api/cron/' "$CRON_FILE" | awk '{print $6}')
    if [ -n "$CRON_AS" ]; then
      if ! id "$CRON_AS" >/dev/null 2>&1; then
        echo "  BROKEN: cron user '$CRON_AS' does not exist — every job fails"; exit 1
      fi
      if [ "$(id -u)" -eq 0 ] && ! runuser -u "$CRON_AS" -- test -r "$ENV_FILE" 2>/dev/null; then
        echo "  BROKEN: '$CRON_AS' cannot read $ENV_FILE — every job fails"; exit 1
      fi
      echo "  runs as: $CRON_AS"
    fi
    echo
    echo "runs in the last 24h (each job logs its own completion):"
    if command -v journalctl >/dev/null 2>&1; then
      journalctl -u flexicaai --since "24 hours ago" 2>/dev/null \
        | grep -o '"op":"cron\.[a-zA-Z]*","msg":"[^"]*"' | sort | uniq -c \
        || echo "  (none — jobs have not fired yet, or the unit name differs)"
    else
      echo "  (journalctl unavailable; check your log destination for '\"op\":\"cron.')"
    fi
    ;;

  core|all)
    need_root
    # A cron line naming a user that doesn't exist fails EVERY run, and only into the
    # system log — exactly the silent failure this script exists to prevent.
    id "$RUN_USER" >/dev/null 2>&1 \
      || die "user '$RUN_USER' does not exist — set RUN_USER=<the user the app runs as>"
    SECRET="$(read_secret)"
    echo "installing the '$MODE' job set as user '$RUN_USER'"
    preflight "$SECRET"

    install -d -m 0755 -o root -g root "$(dirname "$ENV_FILE")"
    umask 077
    printf 'CRON_SECRET=%s\n' "$SECRET" > "$ENV_FILE"
    # root:<run-user> 0640, NOT 0600 root:root — the cron line runs AS $RUN_USER and
    # sources this file, so that user must be able to read it while nobody else can.
    # Owned by root so the app's own user cannot rewrite the secret it authenticates with.
    chown "root:$RUN_USER" "$ENV_FILE"; chmod 0640 "$ENV_FILE"
    echo "  wrote $ENV_FILE (0640 root:$RUN_USER)"

    render "$MODE" > "$CRON_FILE"
    chmod 0644 "$CRON_FILE"; chown root:root "$CRON_FILE"
    echo "  wrote $CRON_FILE ($(grep -c 'api/cron/' "$CRON_FILE") jobs)"

    echo
    echo "done. confirm tomorrow with:"
    echo "  ./deploy/install-cron.sh check"
    [ "$MODE" = "core" ] && echo "note: recalls + reminders are NOT installed — re-run with 'all' once WhatsApp is configured."
    ;;

  *)
    sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
    exit 1
    ;;
esac
